# Generated by Django 5.1.1 on 2024-09-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acervo_pessoal', '0005_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='usuario_portador',
            new_name='usuario',
        ),
    ]
